<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:tx="http://www.springframework.org/schema/tx"
       xmlns:aop="http://www.springframework.org/schema/aop"
       xmlns="http://www.springframework.org/schema/beans"
       xsi:schemaLocation="http://www.springframework.org/schema/beans
	http://www.springframework.org/schema/beans/spring-beans.xsd
	http://www.springframework.org/schema/tx
	http://www.springframework.org/schema/tx/spring-tx.xsd
	http://www.springframework.org/schema/aop
	http://www.springframework.org/schema/aop/spring-aop.xsd">
	<!-- 事务回滚 -->
	<bean id="appTransactionManager" class="org.springframework.jdbc.datasource.DataSourceTransactionManager">
      <property name="dataSource" ref="dataSource" />
    </bean>
	
<!-- 	<aop:config>
		<aop:pointcut id="service" expression="execution(* cn.edu.swust..*Service*.*(..))" />声明所有包含Service的类的所有方法使用事务
		<aop:advisor advice-ref="txAdvice" pointcut-ref="service" />
	</aop:config>
	todo bug  事务回滚 
	<tx:advice id="txAdvice" transaction-manager="appTransactionManager">
		<tx:attributes>
			<tx:method name="get*" read-only="true"  />
			<tx:method name="query*" read-only="true"  />
			<tx:method name="find*" read-only="true" />
			<tx:method name="is*" read-only="true" />
			<tx:method name="insert*" read-only="true" />
			<tx:method name="*" rollback-for="Exception"/>默认回滚机制是RuntimeException
		</tx:attributes>
	</tx:advice> -->

	
    <tx:annotation-driven  transaction-manager="appTransactionManager" />

</beans>